"""add status and timestamps to users

Revision ID: 14e2d4d604e5
Revises: 823abb0c177d
Create Date: 2026-03-25 09:48:29.171763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e2d4d604e5'
down_revision: Union[str, Sequence[str], None] = '823abb0c177d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Integer(), server_default="1"))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
